package com.ekek.tfthobmodule.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALARM_CLOCK_SETTING".
*/
public class AlarmClockSettingDao extends AbstractDao<AlarmClockSetting, Long> {

    public static final String TABLENAME = "ALARM_CLOCK_SETTING";

    /**
     * Properties of entity AlarmClockSetting.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Hour = new Property(1, int.class, "hour", false, "alarm_clock_hour");
        public final static Property Minute = new Property(2, int.class, "minute", false, "alarm_clock_minute");
        public final static Property Reserve = new Property(3, int.class, "reserve", false, "reserve");
    }


    public AlarmClockSettingDao(DaoConfig config) {
        super(config);
    }
    
    public AlarmClockSettingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALARM_CLOCK_SETTING\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"alarm_clock_hour\" INTEGER NOT NULL ," + // 1: hour
                "\"alarm_clock_minute\" INTEGER NOT NULL ," + // 2: minute
                "\"reserve\" INTEGER NOT NULL );"); // 3: reserve
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALARM_CLOCK_SETTING\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AlarmClockSetting entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getHour());
        stmt.bindLong(3, entity.getMinute());
        stmt.bindLong(4, entity.getReserve());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AlarmClockSetting entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getHour());
        stmt.bindLong(3, entity.getMinute());
        stmt.bindLong(4, entity.getReserve());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AlarmClockSetting readEntity(Cursor cursor, int offset) {
        AlarmClockSetting entity = new AlarmClockSetting( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // hour
            cursor.getInt(offset + 2), // minute
            cursor.getInt(offset + 3) // reserve
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AlarmClockSetting entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHour(cursor.getInt(offset + 1));
        entity.setMinute(cursor.getInt(offset + 2));
        entity.setReserve(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AlarmClockSetting entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AlarmClockSetting entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AlarmClockSetting entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
