package com.ekek.tfthobmodule.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ekek.tfthobmodule.entity.AlarmClockSetting;
import com.ekek.tfthobmodule.entity.CookerDataTable;
import com.ekek.tfthobmodule.entity.FishTable;
import com.ekek.tfthobmodule.entity.FruitTable;
import com.ekek.tfthobmodule.entity.HobData;
import com.ekek.tfthobmodule.entity.HoodData;
import com.ekek.tfthobmodule.entity.LegumesAndCerealsTable;
import com.ekek.tfthobmodule.entity.MeatTable;
import com.ekek.tfthobmodule.entity.MyRecipesTable;
import com.ekek.tfthobmodule.entity.Setting;
import com.ekek.tfthobmodule.entity.ShellfishTable;
import com.ekek.tfthobmodule.entity.VegetablesTable;

import com.ekek.tfthobmodule.entity.AlarmClockSettingDao;
import com.ekek.tfthobmodule.entity.CookerDataTableDao;
import com.ekek.tfthobmodule.entity.FishTableDao;
import com.ekek.tfthobmodule.entity.FruitTableDao;
import com.ekek.tfthobmodule.entity.HobDataDao;
import com.ekek.tfthobmodule.entity.HoodDataDao;
import com.ekek.tfthobmodule.entity.LegumesAndCerealsTableDao;
import com.ekek.tfthobmodule.entity.MeatTableDao;
import com.ekek.tfthobmodule.entity.MyRecipesTableDao;
import com.ekek.tfthobmodule.entity.SettingDao;
import com.ekek.tfthobmodule.entity.ShellfishTableDao;
import com.ekek.tfthobmodule.entity.VegetablesTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmClockSettingDaoConfig;
    private final DaoConfig cookerDataTableDaoConfig;
    private final DaoConfig fishTableDaoConfig;
    private final DaoConfig fruitTableDaoConfig;
    private final DaoConfig hobDataDaoConfig;
    private final DaoConfig hoodDataDaoConfig;
    private final DaoConfig legumesAndCerealsTableDaoConfig;
    private final DaoConfig meatTableDaoConfig;
    private final DaoConfig myRecipesTableDaoConfig;
    private final DaoConfig settingDaoConfig;
    private final DaoConfig shellfishTableDaoConfig;
    private final DaoConfig vegetablesTableDaoConfig;

    private final AlarmClockSettingDao alarmClockSettingDao;
    private final CookerDataTableDao cookerDataTableDao;
    private final FishTableDao fishTableDao;
    private final FruitTableDao fruitTableDao;
    private final HobDataDao hobDataDao;
    private final HoodDataDao hoodDataDao;
    private final LegumesAndCerealsTableDao legumesAndCerealsTableDao;
    private final MeatTableDao meatTableDao;
    private final MyRecipesTableDao myRecipesTableDao;
    private final SettingDao settingDao;
    private final ShellfishTableDao shellfishTableDao;
    private final VegetablesTableDao vegetablesTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmClockSettingDaoConfig = daoConfigMap.get(AlarmClockSettingDao.class).clone();
        alarmClockSettingDaoConfig.initIdentityScope(type);

        cookerDataTableDaoConfig = daoConfigMap.get(CookerDataTableDao.class).clone();
        cookerDataTableDaoConfig.initIdentityScope(type);

        fishTableDaoConfig = daoConfigMap.get(FishTableDao.class).clone();
        fishTableDaoConfig.initIdentityScope(type);

        fruitTableDaoConfig = daoConfigMap.get(FruitTableDao.class).clone();
        fruitTableDaoConfig.initIdentityScope(type);

        hobDataDaoConfig = daoConfigMap.get(HobDataDao.class).clone();
        hobDataDaoConfig.initIdentityScope(type);

        hoodDataDaoConfig = daoConfigMap.get(HoodDataDao.class).clone();
        hoodDataDaoConfig.initIdentityScope(type);

        legumesAndCerealsTableDaoConfig = daoConfigMap.get(LegumesAndCerealsTableDao.class).clone();
        legumesAndCerealsTableDaoConfig.initIdentityScope(type);

        meatTableDaoConfig = daoConfigMap.get(MeatTableDao.class).clone();
        meatTableDaoConfig.initIdentityScope(type);

        myRecipesTableDaoConfig = daoConfigMap.get(MyRecipesTableDao.class).clone();
        myRecipesTableDaoConfig.initIdentityScope(type);

        settingDaoConfig = daoConfigMap.get(SettingDao.class).clone();
        settingDaoConfig.initIdentityScope(type);

        shellfishTableDaoConfig = daoConfigMap.get(ShellfishTableDao.class).clone();
        shellfishTableDaoConfig.initIdentityScope(type);

        vegetablesTableDaoConfig = daoConfigMap.get(VegetablesTableDao.class).clone();
        vegetablesTableDaoConfig.initIdentityScope(type);

        alarmClockSettingDao = new AlarmClockSettingDao(alarmClockSettingDaoConfig, this);
        cookerDataTableDao = new CookerDataTableDao(cookerDataTableDaoConfig, this);
        fishTableDao = new FishTableDao(fishTableDaoConfig, this);
        fruitTableDao = new FruitTableDao(fruitTableDaoConfig, this);
        hobDataDao = new HobDataDao(hobDataDaoConfig, this);
        hoodDataDao = new HoodDataDao(hoodDataDaoConfig, this);
        legumesAndCerealsTableDao = new LegumesAndCerealsTableDao(legumesAndCerealsTableDaoConfig, this);
        meatTableDao = new MeatTableDao(meatTableDaoConfig, this);
        myRecipesTableDao = new MyRecipesTableDao(myRecipesTableDaoConfig, this);
        settingDao = new SettingDao(settingDaoConfig, this);
        shellfishTableDao = new ShellfishTableDao(shellfishTableDaoConfig, this);
        vegetablesTableDao = new VegetablesTableDao(vegetablesTableDaoConfig, this);

        registerDao(AlarmClockSetting.class, alarmClockSettingDao);
        registerDao(CookerDataTable.class, cookerDataTableDao);
        registerDao(FishTable.class, fishTableDao);
        registerDao(FruitTable.class, fruitTableDao);
        registerDao(HobData.class, hobDataDao);
        registerDao(HoodData.class, hoodDataDao);
        registerDao(LegumesAndCerealsTable.class, legumesAndCerealsTableDao);
        registerDao(MeatTable.class, meatTableDao);
        registerDao(MyRecipesTable.class, myRecipesTableDao);
        registerDao(Setting.class, settingDao);
        registerDao(ShellfishTable.class, shellfishTableDao);
        registerDao(VegetablesTable.class, vegetablesTableDao);
    }
    
    public void clear() {
        alarmClockSettingDaoConfig.clearIdentityScope();
        cookerDataTableDaoConfig.clearIdentityScope();
        fishTableDaoConfig.clearIdentityScope();
        fruitTableDaoConfig.clearIdentityScope();
        hobDataDaoConfig.clearIdentityScope();
        hoodDataDaoConfig.clearIdentityScope();
        legumesAndCerealsTableDaoConfig.clearIdentityScope();
        meatTableDaoConfig.clearIdentityScope();
        myRecipesTableDaoConfig.clearIdentityScope();
        settingDaoConfig.clearIdentityScope();
        shellfishTableDaoConfig.clearIdentityScope();
        vegetablesTableDaoConfig.clearIdentityScope();
    }

    public AlarmClockSettingDao getAlarmClockSettingDao() {
        return alarmClockSettingDao;
    }

    public CookerDataTableDao getCookerDataTableDao() {
        return cookerDataTableDao;
    }

    public FishTableDao getFishTableDao() {
        return fishTableDao;
    }

    public FruitTableDao getFruitTableDao() {
        return fruitTableDao;
    }

    public HobDataDao getHobDataDao() {
        return hobDataDao;
    }

    public HoodDataDao getHoodDataDao() {
        return hoodDataDao;
    }

    public LegumesAndCerealsTableDao getLegumesAndCerealsTableDao() {
        return legumesAndCerealsTableDao;
    }

    public MeatTableDao getMeatTableDao() {
        return meatTableDao;
    }

    public MyRecipesTableDao getMyRecipesTableDao() {
        return myRecipesTableDao;
    }

    public SettingDao getSettingDao() {
        return settingDao;
    }

    public ShellfishTableDao getShellfishTableDao() {
        return shellfishTableDao;
    }

    public VegetablesTableDao getVegetablesTableDao() {
        return vegetablesTableDao;
    }

}
