package com.ekek.tfthobmodule.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOOD_DATA".
*/
public class HoodDataDao extends AbstractDao<HoodData, Long> {

    public static final String TABLENAME = "HOOD_DATA";

    /**
     * Properties of entity HoodData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FanGear = new Property(1, int.class, "fanGear", false, "fan_gear");
        public final static Property LightGear = new Property(2, int.class, "lightGear", false, "light_gear");
        public final static Property Reserve = new Property(3, int.class, "reserve", false, "reserve");
    }


    public HoodDataDao(DaoConfig config) {
        super(config);
    }
    
    public HoodDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOOD_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"fan_gear\" INTEGER NOT NULL ," + // 1: fanGear
                "\"light_gear\" INTEGER NOT NULL ," + // 2: lightGear
                "\"reserve\" INTEGER NOT NULL );"); // 3: reserve
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOOD_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HoodData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFanGear());
        stmt.bindLong(3, entity.getLightGear());
        stmt.bindLong(4, entity.getReserve());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HoodData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFanGear());
        stmt.bindLong(3, entity.getLightGear());
        stmt.bindLong(4, entity.getReserve());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HoodData readEntity(Cursor cursor, int offset) {
        HoodData entity = new HoodData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // fanGear
            cursor.getInt(offset + 2), // lightGear
            cursor.getInt(offset + 3) // reserve
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HoodData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFanGear(cursor.getInt(offset + 1));
        entity.setLightGear(cursor.getInt(offset + 2));
        entity.setReserve(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HoodData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HoodData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HoodData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
